# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyExchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyExchange

  pod 'SnapKit', '~> 5.7.0'
  pod 'Alamofire'
  pod 'KeychainSwift', '~> 24.0'

end
